resource_group_name         = "howden_rg"
resource_group_location     = "East US"
virtual_network_name        = "howdenvnet"
subnet_name                 = "howdensubnet"
public_ip_name              = "howdenpublicip"
network_security_group_name = "howdennsg"
network_interface_name      = "howdennic"
linux_virtual_machine_name  = "howdenlinuxvm"